const CACHE_NAME = 'teachings-ai-v1';

const urlsToCache = [
  '/',
  '/Grammar.html',
  '/about.html',
  '/alphabets.html',
  '/animals-birds-sorting.html',
  '/animals.html',
  '/assets/audio/background_music.mp3',
  '/assets/audio/click.mp3',
  '/assets/images/app_icon_192.png',
  '/assets/images/app_icon_512.png',
  '/birds.html',
  '/bodyparts.html',
  '/colors.html',
  '/colours-sorting.html',
  '/counting.html',
  '/countries.html',
  '/css/alphabets.css',
  '/css/animals.css',
  '/css/birds.css',
  '/css/bodyparts.css',
  '/css/colors.css',
  '/css/counting.css',
  '/css/fruits.css',
  '/css/grammar copy.css',
  '/css/grammar.css',
  '/css/healthyfoods.css',
  '/css/math.css',
  '/css/numbers.css',
  '/css/oddEven.css',
  '/css/patterns.css',
  '/css/phonics.css',
  '/css/plants.css',
  '/css/publicservice.css',
  '/css/rhyming.css',
  '/css/sentences.css',
  '/css/shapes.css',
  '/css/sight.css',
  '/css/style.css',
  '/css/vegetables.css',
  '/css/vehicles.css',
  '/css/word-matching.css',
  '/disclaimer.html',
  '/downloads.html',
  '/electronic-gadgets.html',
  '/fantasy-world.html',
  '/feedback.html',
  '/fruits-vegetables-sorting.html',
  '/fruits.html',
  '/furits-vegetables-sorting.html',
  '/games.html',
  '/index.html',
  '/js/alphabets.js',
  '/js/animals.js',
  '/js/birds.js',
  '/js/bodyparts.js',
  '/js/colors.js',
  '/js/counting.js',
  '/js/countries.js',
  '/js/electronic-gadgets.js',
  '/js/fantasy-world.js',
  '/js/fruits.js',
  '/js/globalImageLoader.js',
  '/js/grammar.js',
  '/js/healthyfoods.js',
  '/js/imageHelper.js',
  '/js/lanscapes.js',
  '/js/math.js',
  '/js/musicControl.js',
  '/js/numbers.js',
  '/js/oddEven.js',
  '/js/patterns.js',
  '/js/phonics.js',
  '/js/planets.js',
  '/js/plants.js',
  '/js/publicservice.js',
  '/js/rhyming.js',
  '/js/scientists.js',
  '/js/script.js',
  '/js/sentences.js',
  '/js/shapes.js',
  '/js/sight.js',
  '/js/vegetables.js',
  '/js/vehicles.js',
  '/js/word-matching.js',
  '/manifest.json',
  '/match-animals.html',
  '/match-numbers.html',
  '/match-shapes.html',
  '/match-words.html',
  '/math.html',
  '/nature-explorer.html',
  '/numbers-alphabets-sorting.html',
  '/numbers.html',
  '/odd-even-sorting.html',
  '/odd-even.html',
  '/patterns.html',
  '/phonic-letter-sound.html',
  '/phonic-numbers.html',
  '/phonic-words.html',
  '/phonics.html',
  '/planets.html',
  '/plants.html',
  '/privacy-policy.html',
  '/publicservice.html',
  '/rhyming-phonic-words.html',
  '/rhyming.html',
  '/scientists.html',
  '/sentences.html',
  '/shapes.html',
  '/sight.html',
  '/vegetables.html',
  '/vehicles.html',
  '/word-matching.html'
]; // Assets

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      return cache.addAll(urlsToCache);
    })
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(response => {
      return response || fetch(event.request);
    })
  );
});
