"""
Wires the 28 real, on-brand preview cards generated by gen_og_images.py
into the specific pages whose original preview image was broken (fixed
in the earlier "Fix sitewide broken og:image" commit by falling back to
the generic site logo, app_icon_512.png, for lack of anything better at
the time). Now that real topic art exists, these pages get it instead of
the generic square logo -- a proper 1200x630 landscape card reads far
better in a search result or social share.

Only touches og:image, twitter:image, and JSON-LD "image"/"thumbnailUrl"
fields -- explicitly never the JSON-LD "logo" field, which is the site's
actual Organization/publisher logo and must stay app_icon_512.png.

Mapping was reconstructed from the "Fix sitewide broken og:image..."
commit's diff (git show 77c4d8b), matching each now-fixed broken
filename back to the exact page(s) it originally appeared on.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRY_RUN = "--dry-run" in sys.argv

GENERIC = "https://www.teachings.ai/assets/images/app_icon_512.png"

PAGE_TO_SLUG = {
    "nature-explorer.html": "vegetables",
    "vegetables.html": "vegetables",
    "alphabets.html": "alphabet-collection",
    "countries.html": "countries",
    "downloads.html": "worksheet-cover",
    "electronic-gadgets.html": "electronic-gadgets",
    "fantasy-world.html": "fantasy-characters",
    "learn/alphabets/index.html": "alphabet-collection",
    "learn/animals/index.html": "animal-collection",
    "learn/birds/index.html": "bird-collection",
    "learn/body-parts/index.html": "body-collection",
    "learn/colors/index.html": "rainbow-collage",
    "learn/country/index.html": "world-map-collage",
    "learn/electronics/index.html": "tech-collage",
    "learn/fruits/index.html": "fruit-basket-collage",
    "learn/index.html": "learning-hub-banner",
    "learn/planets/index.html": "solar-system-collage",
    "learn/vegetables/index.html": "veggie-basket-collage",
    "learn/vehicles/index.html": "vehicle-collage",
    "odd-even.html": "odd-even-preview",
    "planets.html": "planets-preview",
    "plants.html": "plants-cover",
    "publicservice.html": "publicservice-preview",
    "rhyming.html": "rhyming-preview",
    "scientists.html": "scientists-preview",
    "shapes.html": "shapes-cover",
    "sight.html": "sight-words-preview",
    "vehicles.html": "vehicles-preview",
    "word-matching.html": "word-matching-preview",
}

FIELD_PATTERNS = [
    re.compile(r'(<meta property="og:image" content=")' + re.escape(GENERIC) + r'(")'),
    re.compile(r'(<meta name="twitter:image" content=")' + re.escape(GENERIC) + r'(")'),
    re.compile(r'("image":\s*")' + re.escape(GENERIC) + r'(")'),
    re.compile(r'("thumbnailUrl":\s*")' + re.escape(GENERIC) + r'(")'),
]


def main():
    changed = []
    for page, slug in PAGE_TO_SLUG.items():
        fp = os.path.join(ROOT, page)
        if not os.path.isfile(fp):
            print(f"MISSING FILE: {page}")
            continue
        with open(fp, "r", encoding="utf-8", errors="ignore") as fh:
            content = fh.read()
        new_url = f"https://www.teachings.ai/assets/images/og/{slug}.jpg"
        count = 0
        for pattern in FIELD_PATTERNS:
            content, n = pattern.subn(lambda m: m.group(1) + new_url + m.group(2), content)
            count += n
        if count:
            changed.append((page, slug, count))
            if not DRY_RUN:
                with open(fp, "w", encoding="utf-8", newline="") as fh:
                    fh.write(content)

    print(f"{'[DRY RUN] ' if DRY_RUN else ''}Pages updated: {len(changed)}")
    for page, slug, count in changed:
        print(f"  {page} -> og/{slug}.jpg ({count} fields)")


if __name__ == "__main__":
    main()
